<?php
/**
 * Shortcodes Defaults
 *
 * @package Lambry\Shorts
 */

namespace Lambry\Shorts;

if ( ! defined( 'WPINC' ) ) die;

/* Defaults Class */
class Defaults {

    /**
     * Colors
     *
     * @access public
     * @return array $colors
     */
    public static function colors() {

        $colors = [
            'blue'   => __( 'Blue', 'lambry-shorts' ),
            'green'  => __( 'Green', 'lambry-shorts' ),
            'orange' => __( 'Orange', 'lambry-shorts' ),
            'yellow' => __( 'Yellow', 'lambry-shorts' ),
            'red'    => __( 'Red', 'lambry-shorts' ),
            'silver' => __( 'Silver', 'lambry-shorts' ),
            'grey'   => __( 'Grey', 'lambry-shorts' ),
            'black'  => __( 'Black', 'lambry-shorts' ),
            'white'  => __( 'White', 'lambry-shorts' )
        ];

        return apply_filters( 'lambry_shorts_colors', $colors );

    }

    /**
     * Sizes
     *
     * @access public
     * @return array $sizes
     */
    public static function sizes() {

        $sizes = [
            'small'  => __( 'Small', 'lambry-shorts' ),
            'medium' => __( 'Medium', 'lambry-shorts' ),
            'large'  => __( 'Large', 'lambry-shorts' ),
            'huge'   => __( 'Huge', 'lambry-shorts' )
        ];

        return apply_filters( 'lambry_shorts_sizes', $sizes );

    }

    /**
     * Grid
     *
     * @access public
     * @return array $grid
     */
    public static function grid() {

        $grid = [
            '1'  => __( 'One Twelth', 'lambry-shorts' ),
            '2'  => __( 'Two Twelths', 'lambry-shorts' ),
            '3'  => __( 'Three Twelths', 'lambry-shorts' ),
            '4'  => __( 'Four Twelths', 'lambry-shorts' ),
            '5'  => __( 'Five Twelths', 'lambry-shorts' ),
            '6'  => __( 'Six Twelths', 'lambry-shorts' ),
            '7'  => __( 'Seven Twelths', 'lambry-shorts' ),
            '8'  => __( 'Eight Twelths', 'lambry-shorts' ),
            '9'  => __( 'Nine Twelths', 'lambry-shorts' ),
            '10' => __( 'Ten Twelths', 'lambry-shorts' ),
            '11' => __( 'Eleven Twelths', 'lambry-shorts' ),
            '12' => __( 'Twelve Twelths', 'lambry-shorts' )
        ];

        return apply_filters( 'lambry_shorts_grid', $grid );

    }

	/**
	 * Align
	 *
	 * @access public
	 * @return array $align
	 */
	public static function align() {

		$alignment = [
			'left'   => __( 'Left', 'lambry-shorts' ),
			'right'  => __( 'Right', 'lambry-shorts' ),
			'center' => __( 'Center', 'lambry-shorts' )
		];

		return apply_filters( 'lambry_shorts_align', $alignment );

	}

    /**
     * Target
     *
     * @access public
     * @return array $target
     */
    public static function target() {

        $target = [
            'self'  => __( 'Default', 'lambry-shorts' ),
            'blank' => __( 'New Window', 'lambry-shorts' )
        ];

        return apply_filters( 'lambry_shorts_target', $target );

    }

    /**
     * Roles
     *
     * @access public
     * @return array $roles
     */
    public static function roles() {

        $wp_roles = get_editable_roles();

        $roles = array_map( function( $item ) {
            return $item['name'];
        }, $wp_roles );

        unset( $roles['administrator'] );

        return apply_filters( 'lambry_shorts_roles', $roles );

    }

    /**
     * Types
     *
     * @access public
     * @return array $types
     */
    public static function types() {

        $types = get_post_types();

        return apply_filters( 'lambry_shorts_types', $types );

    }

    /**
	 * Icons
     *
     * @access public
     * @return array $icons
	 */
	public static function icons() {

		$icons = [
            '500px' => __( '500px', 'lambry-shorts' ),
            'adjust' => __( 'Adjust', 'lambry-shorts' ),
            'adn' => __( 'Adn', 'lambry-shorts' ),
            'align-center' => __( 'Align Center', 'lambry-shorts' ),
            'align-justify' => __( 'Align Justify', 'lambry-shorts' ),
            'align-left' => __( 'Align Left', 'lambry-shorts' ),
            'align-right' => __( 'Align Right', 'lambry-shorts' ),
            'amazon' => __( 'Amazon', 'lambry-shorts' ),
            'ambulance' => __( 'Ambulance', 'lambry-shorts' ),
            'anchor' => __( 'Anchor', 'lambry-shorts' ),
            'android' => __( 'Android', 'lambry-shorts' ),
            'angellist' => __( 'Angellist', 'lambry-shorts' ),
            'angle-double-down' => __( 'Angle Double Down', 'lambry-shorts' ),
            'angle-double-left' => __( 'Angle Double Left', 'lambry-shorts' ),
            'angle-double-right' => __( 'Angle Double Right', 'lambry-shorts' ),
            'angle-double-up' => __( 'Angle Double Up', 'lambry-shorts' ),
            'angle-down' => __( 'Angle Down', 'lambry-shorts' ),
            'angle-left' => __( 'Angle Left', 'lambry-shorts' ),
            'angle-right' => __( 'Angle Right', 'lambry-shorts' ),
            'angle-up' => __( 'Angle Up', 'lambry-shorts' ),
            'apple' => __( 'Apple', 'lambry-shorts' ),
            'archive' => __( 'Archive', 'lambry-shorts' ),
            'area-chart' => __( 'Area Chart', 'lambry-shorts' ),
            'arrow-circle-down' => __( 'Arrow Circle Down', 'lambry-shorts' ),
            'arrow-circle-left' => __( 'Arrow Circle Left', 'lambry-shorts' ),
            'arrow-circle-o-down' => __( 'Arrow Circle O Down', 'lambry-shorts' ),
            'arrow-circle-o-left' => __( 'Arrow Circle O Left', 'lambry-shorts' ),
            'arrow-circle-o-right' => __( 'Arrow Circle O Right', 'lambry-shorts' ),
            'arrow-circle-o-up' => __( 'Arrow Circle O Up', 'lambry-shorts' ),
            'arrow-circle-right' => __( 'Arrow Circle Right', 'lambry-shorts' ),
            'arrow-circle-up' => __( 'Arrow Circle Up', 'lambry-shorts' ),
            'arrow-down' => __( 'Arrow Down', 'lambry-shorts' ),
            'arrow-left' => __( 'Arrow Left', 'lambry-shorts' ),
            'arrow-right' => __( 'Arrow Right', 'lambry-shorts' ),
            'arrow-up' => __( 'Arrow Up', 'lambry-shorts' ),
            'arrows' => __( 'Arrows', 'lambry-shorts' ),
            'arrows-alt' => __( 'Arrows Alt', 'lambry-shorts' ),
            'arrows-h' => __( 'Arrows H', 'lambry-shorts' ),
            'arrows-v' => __( 'Arrows V', 'lambry-shorts' ),
            'asterisk' => __( 'Asterisk', 'lambry-shorts' ),
            'at' => __( 'At', 'lambry-shorts' ),
            'backward' => __( 'Backward', 'lambry-shorts' ),
            'balance-scale' => __( 'Balance Scale', 'lambry-shorts' ),
            'ban' => __( 'Ban', 'lambry-shorts' ),
            'bar-chart' => __( 'Bar Chart', 'lambry-shorts' ),
            'barcode' => __( 'Barcode', 'lambry-shorts' ),
            'bars' => __( 'Bars', 'lambry-shorts' ),
            'battery-empty' => __( 'Battery Empty', 'lambry-shorts' ),
            'battery-full' => __( 'Battery Full', 'lambry-shorts' ),
            'battery-half' => __( 'Battery Half', 'lambry-shorts' ),
            'battery-quarter' => __( 'Battery Quarter', 'lambry-shorts' ),
            'battery-three-quarters' => __( 'Battery Three Quarters', 'lambry-shorts' ),
            'bed' => __( 'Bed', 'lambry-shorts' ),
            'beer' => __( 'Beer', 'lambry-shorts' ),
            'behance' => __( 'Behance', 'lambry-shorts' ),
            'behance-square' => __( 'Behance Square', 'lambry-shorts' ),
            'bell' => __( 'Bell', 'lambry-shorts' ),
            'bell-o' => __( 'Bell O', 'lambry-shorts' ),
            'bell-slash' => __( 'Bell Slash', 'lambry-shorts' ),
            'bell-slash-o' => __( 'Bell Slash O', 'lambry-shorts' ),
            'bicycle' => __( 'Bicycle', 'lambry-shorts' ),
            'binoculars' => __( 'Binoculars', 'lambry-shorts' ),
            'birthday-cake' => __( 'Birthday Cake', 'lambry-shorts' ),
            'bitbucket' => __( 'Bitbucket', 'lambry-shorts' ),
            'bitbucket-square' => __( 'Bitbucket Square', 'lambry-shorts' ),
            'black-tie' => __( 'Black Tie', 'lambry-shorts' ),
            'bold' => __( 'Bold', 'lambry-shorts' ),
            'bolt' => __( 'Bolt', 'lambry-shorts' ),
            'bomb' => __( 'Bomb', 'lambry-shorts' ),
            'book' => __( 'Book', 'lambry-shorts' ),
            'bookmark' => __( 'Bookmark', 'lambry-shorts' ),
            'bookmark-o' => __( 'Bookmark O', 'lambry-shorts' ),
            'briefcase' => __( 'Briefcase', 'lambry-shorts' ),
            'btc' => __( 'Btc', 'lambry-shorts' ),
            'bug' => __( 'Bug', 'lambry-shorts' ),
            'building' => __( 'Building', 'lambry-shorts' ),
            'building-o' => __( 'Building O', 'lambry-shorts' ),
            'bullhorn' => __( 'Bullhorn', 'lambry-shorts' ),
            'bullseye' => __( 'Bullseye', 'lambry-shorts' ),
            'bus' => __( 'Bus', 'lambry-shorts' ),
            'buysellads' => __( 'Buysellads', 'lambry-shorts' ),
            'calculator' => __( 'Calculator', 'lambry-shorts' ),
            'calendar' => __( 'Calendar', 'lambry-shorts' ),
            'calendar-check-o' => __( 'Calendar Check O', 'lambry-shorts' ),
            'calendar-minus-o' => __( 'Calendar Minus O', 'lambry-shorts' ),
            'calendar-o' => __( 'Calendar O', 'lambry-shorts' ),
            'calendar-plus-o' => __( 'Calendar Plus O', 'lambry-shorts' ),
            'calendar-times-o' => __( 'Calendar Times O', 'lambry-shorts' ),
            'camera' => __( 'Camera', 'lambry-shorts' ),
            'camera-retro' => __( 'Camera Retro', 'lambry-shorts' ),
            'car' => __( 'Car', 'lambry-shorts' ),
            'caret-down' => __( 'Caret Down', 'lambry-shorts' ),
            'caret-left' => __( 'Caret Left', 'lambry-shorts' ),
            'caret-right' => __( 'Caret Right', 'lambry-shorts' ),
            'caret-square-o-down' => __( 'Caret Square O Down', 'lambry-shorts' ),
            'caret-square-o-left' => __( 'Caret Square O Left', 'lambry-shorts' ),
            'caret-square-o-right' => __( 'Caret Square O Right', 'lambry-shorts' ),
            'caret-square-o-up' => __( 'Caret Square O Up', 'lambry-shorts' ),
            'caret-up' => __( 'Caret Up', 'lambry-shorts' ),
            'cart-arrow-down' => __( 'Cart Arrow Down', 'lambry-shorts' ),
            'cart-plus' => __( 'Cart Plus', 'lambry-shorts' ),
            'cc' => __( 'Cc', 'lambry-shorts' ),
            'cc-amex' => __( 'Cc Amex', 'lambry-shorts' ),
            'cc-diners-club' => __( 'Cc Diners Club', 'lambry-shorts' ),
            'cc-discover' => __( 'Cc Discover', 'lambry-shorts' ),
            'cc-jcb' => __( 'Cc Jcb', 'lambry-shorts' ),
            'cc-mastercard' => __( 'Cc Mastercard', 'lambry-shorts' ),
            'cc-paypal' => __( 'Cc Paypal', 'lambry-shorts' ),
            'cc-stripe' => __( 'Cc Stripe', 'lambry-shorts' ),
            'cc-visa' => __( 'Cc Visa', 'lambry-shorts' ),
            'certificate' => __( 'Certificate', 'lambry-shorts' ),
            'chain-broken' => __( 'Chain Broken', 'lambry-shorts' ),
            'check' => __( 'Check', 'lambry-shorts' ),
            'check-circle' => __( 'Check Circle', 'lambry-shorts' ),
            'check-circle-o' => __( 'Check Circle O', 'lambry-shorts' ),
            'check-square' => __( 'Check Square', 'lambry-shorts' ),
            'check-square-o' => __( 'Check Square O', 'lambry-shorts' ),
            'chevron-circle-down' => __( 'Chevron Circle Down', 'lambry-shorts' ),
            'chevron-circle-left' => __( 'Chevron Circle Left', 'lambry-shorts' ),
            'chevron-circle-right' => __( 'Chevron Circle Right', 'lambry-shorts' ),
            'chevron-circle-up' => __( 'Chevron Circle Up', 'lambry-shorts' ),
            'chevron-down' => __( 'Chevron Down', 'lambry-shorts' ),
            'chevron-left' => __( 'Chevron Left', 'lambry-shorts' ),
            'chevron-right' => __( 'Chevron Right', 'lambry-shorts' ),
            'chevron-up' => __( 'Chevron Up', 'lambry-shorts' ),
            'child' => __( 'Child', 'lambry-shorts' ),
            'chrome' => __( 'Chrome', 'lambry-shorts' ),
            'circle' => __( 'Circle', 'lambry-shorts' ),
            'circle-o' => __( 'Circle O', 'lambry-shorts' ),
            'circle-o-notch' => __( 'Circle O Notch', 'lambry-shorts' ),
            'circle-thin' => __( 'Circle Thin', 'lambry-shorts' ),
            'clipboard' => __( 'Clipboard', 'lambry-shorts' ),
            'clock-o' => __( 'Clock O', 'lambry-shorts' ),
            'clone' => __( 'Clone', 'lambry-shorts' ),
            'cloud' => __( 'Cloud', 'lambry-shorts' ),
            'cloud-download' => __( 'Cloud Download', 'lambry-shorts' ),
            'cloud-upload' => __( 'Cloud Upload', 'lambry-shorts' ),
            'code' => __( 'Code', 'lambry-shorts' ),
            'code-fork' => __( 'Code Fork', 'lambry-shorts' ),
            'codepen' => __( 'Codepen', 'lambry-shorts' ),
            'coffee' => __( 'Coffee', 'lambry-shorts' ),
            'cog' => __( 'Cog', 'lambry-shorts' ),
            'cogs' => __( 'Cogs', 'lambry-shorts' ),
            'columns' => __( 'Columns', 'lambry-shorts' ),
            'comment' => __( 'Comment', 'lambry-shorts' ),
            'comment-o' => __( 'Comment O', 'lambry-shorts' ),
            'commenting' => __( 'Commenting', 'lambry-shorts' ),
            'commenting-o' => __( 'Commenting O', 'lambry-shorts' ),
            'comments' => __( 'Comments', 'lambry-shorts' ),
            'comments-o' => __( 'Comments O', 'lambry-shorts' ),
            'compass' => __( 'Compass', 'lambry-shorts' ),
            'compress' => __( 'Compress', 'lambry-shorts' ),
            'connectdevelop' => __( 'Connectdevelop', 'lambry-shorts' ),
            'contao' => __( 'Contao', 'lambry-shorts' ),
            'copyright' => __( 'Copyright', 'lambry-shorts' ),
            'creative-commons' => __( 'Creative Commons', 'lambry-shorts' ),
            'credit-card' => __( 'Credit Card', 'lambry-shorts' ),
            'crop' => __( 'Crop', 'lambry-shorts' ),
            'crosshairs' => __( 'Crosshairs', 'lambry-shorts' ),
            'css3' => __( 'Css3', 'lambry-shorts' ),
            'cube' => __( 'Cube', 'lambry-shorts' ),
            'cubes' => __( 'Cubes', 'lambry-shorts' ),
            'cutlery' => __( 'Cutlery', 'lambry-shorts' ),
            'dashcube' => __( 'Dashcube', 'lambry-shorts' ),
            'database' => __( 'Database', 'lambry-shorts' ),
            'delicious' => __( 'Delicious', 'lambry-shorts' ),
            'desktop' => __( 'Desktop', 'lambry-shorts' ),
            'deviantart' => __( 'Deviantart', 'lambry-shorts' ),
            'diamond' => __( 'Diamond', 'lambry-shorts' ),
            'digg' => __( 'Digg', 'lambry-shorts' ),
            'dot-circle-o' => __( 'Dot Circle O', 'lambry-shorts' ),
            'download' => __( 'Download', 'lambry-shorts' ),
            'dribbble' => __( 'Dribbble', 'lambry-shorts' ),
            'dropbox' => __( 'Dropbox', 'lambry-shorts' ),
            'drupal' => __( 'Drupal', 'lambry-shorts' ),
            'eject' => __( 'Eject', 'lambry-shorts' ),
            'ellipsis-h' => __( 'Ellipsis H', 'lambry-shorts' ),
            'ellipsis-v' => __( 'Ellipsis V', 'lambry-shorts' ),
            'empire' => __( 'Empire', 'lambry-shorts' ),
            'envelope' => __( 'Envelope', 'lambry-shorts' ),
            'envelope-o' => __( 'Envelope O', 'lambry-shorts' ),
            'envelope-square' => __( 'Envelope Square', 'lambry-shorts' ),
            'eraser' => __( 'Eraser', 'lambry-shorts' ),
            'eur' => __( 'Eur', 'lambry-shorts' ),
            'exchange' => __( 'Exchange', 'lambry-shorts' ),
            'exclamation' => __( 'Exclamation', 'lambry-shorts' ),
            'exclamation-circle' => __( 'Exclamation Circle', 'lambry-shorts' ),
            'exclamation-triangle' => __( 'Exclamation Triangle', 'lambry-shorts' ),
            'expand' => __( 'Expand', 'lambry-shorts' ),
            'expeditedssl' => __( 'Expeditedssl', 'lambry-shorts' ),
            'external-link' => __( 'External Link', 'lambry-shorts' ),
            'external-link-square' => __( 'External Link Square', 'lambry-shorts' ),
            'eye' => __( 'Eye', 'lambry-shorts' ),
            'eye-slash' => __( 'Eye Slash', 'lambry-shorts' ),
            'eyedropper' => __( 'Eyedropper', 'lambry-shorts' ),
            'facebook' => __( 'Facebook', 'lambry-shorts' ),
            'facebook-official' => __( 'Facebook Official', 'lambry-shorts' ),
            'facebook-square' => __( 'Facebook Square', 'lambry-shorts' ),
            'fast-backward' => __( 'Fast Backward', 'lambry-shorts' ),
            'fast-forward' => __( 'Fast Forward', 'lambry-shorts' ),
            'fax' => __( 'Fax', 'lambry-shorts' ),
            'female' => __( 'Female', 'lambry-shorts' ),
            'fighter-jet' => __( 'Fighter Jet', 'lambry-shorts' ),
            'file' => __( 'File', 'lambry-shorts' ),
            'file-archive-o' => __( 'File Archive O', 'lambry-shorts' ),
            'file-audio-o' => __( 'File Audio O', 'lambry-shorts' ),
            'file-code-o' => __( 'File Code O', 'lambry-shorts' ),
            'file-excel-o' => __( 'File Excel O', 'lambry-shorts' ),
            'file-image-o' => __( 'File Image O', 'lambry-shorts' ),
            'file-o' => __( 'File O', 'lambry-shorts' ),
            'file-pdf-o' => __( 'File Pdf O', 'lambry-shorts' ),
            'file-powerpoint-o' => __( 'File Powerpoint O', 'lambry-shorts' ),
            'file-text' => __( 'File Text', 'lambry-shorts' ),
            'file-text-o' => __( 'File Text O', 'lambry-shorts' ),
            'file-video-o' => __( 'File Video O', 'lambry-shorts' ),
            'file-word-o' => __( 'File Word O', 'lambry-shorts' ),
            'files-o' => __( 'Files O', 'lambry-shorts' ),
            'film' => __( 'Film', 'lambry-shorts' ),
            'filter' => __( 'Filter', 'lambry-shorts' ),
            'fire' => __( 'Fire', 'lambry-shorts' ),
            'fire-extinguisher' => __( 'Fire Extinguisher', 'lambry-shorts' ),
            'firefox' => __( 'Firefox', 'lambry-shorts' ),
            'flag' => __( 'Flag', 'lambry-shorts' ),
            'flag-checkered' => __( 'Flag Checkered', 'lambry-shorts' ),
            'flag-o' => __( 'Flag O', 'lambry-shorts' ),
            'flask' => __( 'Flask', 'lambry-shorts' ),
            'flickr' => __( 'Flickr', 'lambry-shorts' ),
            'floppy-o' => __( 'Floppy O', 'lambry-shorts' ),
            'folder' => __( 'Folder', 'lambry-shorts' ),
            'folder-o' => __( 'Folder O', 'lambry-shorts' ),
            'folder-open' => __( 'Folder Open', 'lambry-shorts' ),
            'folder-open-o' => __( 'Folder Open O', 'lambry-shorts' ),
            'font' => __( 'Font', 'lambry-shorts' ),
            'fonticons' => __( 'Fonticons', 'lambry-shorts' ),
            'forumbee' => __( 'Forumbee', 'lambry-shorts' ),
            'forward' => __( 'Forward', 'lambry-shorts' ),
            'foursquare' => __( 'Foursquare', 'lambry-shorts' ),
            'frown-o' => __( 'Frown O', 'lambry-shorts' ),
            'futbol-o' => __( 'Futbol O', 'lambry-shorts' ),
            'gamepad' => __( 'Gamepad', 'lambry-shorts' ),
            'gavel' => __( 'Gavel', 'lambry-shorts' ),
            'gbp' => __( 'Gbp', 'lambry-shorts' ),
            'genderless' => __( 'Genderless', 'lambry-shorts' ),
            'get-pocket' => __( 'Get Pocket', 'lambry-shorts' ),
            'gg' => __( 'Gg', 'lambry-shorts' ),
            'gg-circle' => __( 'Gg Circle', 'lambry-shorts' ),
            'gift' => __( 'Gift', 'lambry-shorts' ),
            'git' => __( 'Git', 'lambry-shorts' ),
            'git-square' => __( 'Git Square', 'lambry-shorts' ),
            'github' => __( 'Github', 'lambry-shorts' ),
            'github-alt' => __( 'Github Alt', 'lambry-shorts' ),
            'github-square' => __( 'Github Square', 'lambry-shorts' ),
            'glass' => __( 'Glass', 'lambry-shorts' ),
            'globe' => __( 'Globe', 'lambry-shorts' ),
            'google' => __( 'Google', 'lambry-shorts' ),
            'google-plus' => __( 'Google Plus', 'lambry-shorts' ),
            'google-plus-square' => __( 'Google Plus Square', 'lambry-shorts' ),
            'google-wallet' => __( 'Google Wallet', 'lambry-shorts' ),
            'graduation-cap' => __( 'Graduation Cap', 'lambry-shorts' ),
            'gratipay' => __( 'Gratipay', 'lambry-shorts' ),
            'h-square' => __( 'H Square', 'lambry-shorts' ),
            'hacker-news' => __( 'Hacker News', 'lambry-shorts' ),
            'hand-lizard-o' => __( 'Hand Lizard O', 'lambry-shorts' ),
            'hand-o-down' => __( 'Hand O Down', 'lambry-shorts' ),
            'hand-o-left' => __( 'Hand O Left', 'lambry-shorts' ),
            'hand-o-right' => __( 'Hand O Right', 'lambry-shorts' ),
            'hand-o-up' => __( 'Hand O Up', 'lambry-shorts' ),
            'hand-paper-o' => __( 'Hand Paper O', 'lambry-shorts' ),
            'hand-peace-o' => __( 'Hand Peace O', 'lambry-shorts' ),
            'hand-pointer-o' => __( 'Hand Pointer O', 'lambry-shorts' ),
            'hand-rock-o' => __( 'Hand Rock O', 'lambry-shorts' ),
            'hand-scissors-o' => __( 'Hand Scissors O', 'lambry-shorts' ),
            'hand-spock-o' => __( 'Hand Spock O', 'lambry-shorts' ),
            'hdd-o' => __( 'Hdd O', 'lambry-shorts' ),
            'header' => __( 'Header', 'lambry-shorts' ),
            'headphones' => __( 'Headphones', 'lambry-shorts' ),
            'heart' => __( 'Heart', 'lambry-shorts' ),
            'heart-o' => __( 'Heart O', 'lambry-shorts' ),
            'heartbeat' => __( 'Heartbeat', 'lambry-shorts' ),
            'history' => __( 'History', 'lambry-shorts' ),
            'home' => __( 'Home', 'lambry-shorts' ),
            'hospital-o' => __( 'Hospital O', 'lambry-shorts' ),
            'hourglass' => __( 'Hourglass', 'lambry-shorts' ),
            'hourglass-end' => __( 'Hourglass End', 'lambry-shorts' ),
            'hourglass-half' => __( 'Hourglass Half', 'lambry-shorts' ),
            'hourglass-o' => __( 'Hourglass O', 'lambry-shorts' ),
            'hourglass-start' => __( 'Hourglass Start', 'lambry-shorts' ),
            'houzz' => __( 'Houzz', 'lambry-shorts' ),
            'html5' => __( 'Html5', 'lambry-shorts' ),
            'i-cursor' => __( 'I Cursor', 'lambry-shorts' ),
            'ils' => __( 'Ils', 'lambry-shorts' ),
            'inbox' => __( 'Inbox', 'lambry-shorts' ),
            'indent' => __( 'Indent', 'lambry-shorts' ),
            'industry' => __( 'Industry', 'lambry-shorts' ),
            'info' => __( 'Info', 'lambry-shorts' ),
            'info-circle' => __( 'Info Circle', 'lambry-shorts' ),
            'inr' => __( 'Inr', 'lambry-shorts' ),
            'instagram' => __( 'Instagram', 'lambry-shorts' ),
            'internet-explorer' => __( 'Internet Explorer', 'lambry-shorts' ),
            'ioxhost' => __( 'Ioxhost', 'lambry-shorts' ),
            'italic' => __( 'Italic', 'lambry-shorts' ),
            'joomla' => __( 'Joomla', 'lambry-shorts' ),
            'jpy' => __( 'Jpy', 'lambry-shorts' ),
            'jsfiddle' => __( 'Jsfiddle', 'lambry-shorts' ),
            'key' => __( 'Key', 'lambry-shorts' ),
            'keyboard-o' => __( 'Keyboard O', 'lambry-shorts' ),
            'krw' => __( 'Krw', 'lambry-shorts' ),
            'language' => __( 'Language', 'lambry-shorts' ),
            'laptop' => __( 'Laptop', 'lambry-shorts' ),
            'lastfm' => __( 'Lastfm', 'lambry-shorts' ),
            'lastfm-square' => __( 'Lastfm Square', 'lambry-shorts' ),
            'leaf' => __( 'Leaf', 'lambry-shorts' ),
            'leanpub' => __( 'Leanpub', 'lambry-shorts' ),
            'lemon-o' => __( 'Lemon O', 'lambry-shorts' ),
            'level-down' => __( 'Level Down', 'lambry-shorts' ),
            'level-up' => __( 'Level Up', 'lambry-shorts' ),
            'life-ring' => __( 'Life Ring', 'lambry-shorts' ),
            'lightbulb-o' => __( 'Lightbulb O', 'lambry-shorts' ),
            'line-chart' => __( 'Line Chart', 'lambry-shorts' ),
            'link' => __( 'Link', 'lambry-shorts' ),
            'linkedin' => __( 'Linkedin', 'lambry-shorts' ),
            'linkedin-square' => __( 'Linkedin Square', 'lambry-shorts' ),
            'linux' => __( 'Linux', 'lambry-shorts' ),
            'list' => __( 'List', 'lambry-shorts' ),
            'list-alt' => __( 'List Alt', 'lambry-shorts' ),
            'list-ol' => __( 'List Ol', 'lambry-shorts' ),
            'list-ul' => __( 'List Ul', 'lambry-shorts' ),
            'location-arrow' => __( 'Location Arrow', 'lambry-shorts' ),
            'lock' => __( 'Lock', 'lambry-shorts' ),
            'long-arrow-down' => __( 'Long Arrow Down', 'lambry-shorts' ),
            'long-arrow-left' => __( 'Long Arrow Left', 'lambry-shorts' ),
            'long-arrow-right' => __( 'Long Arrow Right', 'lambry-shorts' ),
            'long-arrow-up' => __( 'Long Arrow Up', 'lambry-shorts' ),
            'magic' => __( 'Magic', 'lambry-shorts' ),
            'magnet' => __( 'Magnet', 'lambry-shorts' ),
            'male' => __( 'Male', 'lambry-shorts' ),
            'map' => __( 'Map', 'lambry-shorts' ),
            'map-marker' => __( 'Map Marker', 'lambry-shorts' ),
            'map-o' => __( 'Map O', 'lambry-shorts' ),
            'map-pin' => __( 'Map Pin', 'lambry-shorts' ),
            'map-signs' => __( 'Map Signs', 'lambry-shorts' ),
            'mars' => __( 'Mars', 'lambry-shorts' ),
            'mars-double' => __( 'Mars Double', 'lambry-shorts' ),
            'mars-stroke' => __( 'Mars Stroke', 'lambry-shorts' ),
            'mars-stroke-h' => __( 'Mars Stroke H', 'lambry-shorts' ),
            'mars-stroke-v' => __( 'Mars Stroke V', 'lambry-shorts' ),
            'maxcdn' => __( 'Maxcdn', 'lambry-shorts' ),
            'meanpath' => __( 'Meanpath', 'lambry-shorts' ),
            'medium' => __( 'Medium', 'lambry-shorts' ),
            'medkit' => __( 'Medkit', 'lambry-shorts' ),
            'meh-o' => __( 'Meh O', 'lambry-shorts' ),
            'mercury' => __( 'Mercury', 'lambry-shorts' ),
            'microphone' => __( 'Microphone', 'lambry-shorts' ),
            'microphone-slash' => __( 'Microphone Slash', 'lambry-shorts' ),
            'minus' => __( 'Minus', 'lambry-shorts' ),
            'minus-circle' => __( 'Minus Circle', 'lambry-shorts' ),
            'minus-square' => __( 'Minus Square', 'lambry-shorts' ),
            'minus-square-o' => __( 'Minus Square O', 'lambry-shorts' ),
            'mobile' => __( 'Mobile', 'lambry-shorts' ),
            'money' => __( 'Money', 'lambry-shorts' ),
            'moon-o' => __( 'Moon O', 'lambry-shorts' ),
            'motorcycle' => __( 'Motorcycle', 'lambry-shorts' ),
            'mouse-pointer' => __( 'Mouse Pointer', 'lambry-shorts' ),
            'music' => __( 'Music', 'lambry-shorts' ),
            'neuter' => __( 'Neuter', 'lambry-shorts' ),
            'newspaper-o' => __( 'Newspaper O', 'lambry-shorts' ),
            'object-group' => __( 'Object Group', 'lambry-shorts' ),
            'object-ungroup' => __( 'Object Ungroup', 'lambry-shorts' ),
            'odnoklassniki' => __( 'Odnoklassniki', 'lambry-shorts' ),
            'odnoklassniki-square' => __( 'Odnoklassniki Square', 'lambry-shorts' ),
            'opencart' => __( 'Opencart', 'lambry-shorts' ),
            'openid' => __( 'Openid', 'lambry-shorts' ),
            'opera' => __( 'Opera', 'lambry-shorts' ),
            'optin-monster' => __( 'Optin Monster', 'lambry-shorts' ),
            'outdent' => __( 'Outdent', 'lambry-shorts' ),
            'pagelines' => __( 'Pagelines', 'lambry-shorts' ),
            'paint-brush' => __( 'Paint Brush', 'lambry-shorts' ),
            'paper-plane' => __( 'Paper Plane', 'lambry-shorts' ),
            'paper-plane-o' => __( 'Paper Plane O', 'lambry-shorts' ),
            'paperclip' => __( 'Paperclip', 'lambry-shorts' ),
            'paragraph' => __( 'Paragraph', 'lambry-shorts' ),
            'pause' => __( 'Pause', 'lambry-shorts' ),
            'paw' => __( 'Paw', 'lambry-shorts' ),
            'paypal' => __( 'Paypal', 'lambry-shorts' ),
            'pencil' => __( 'Pencil', 'lambry-shorts' ),
            'pencil-square' => __( 'Pencil Square', 'lambry-shorts' ),
            'pencil-square-o' => __( 'Pencil Square O', 'lambry-shorts' ),
            'phone' => __( 'Phone', 'lambry-shorts' ),
            'phone-square' => __( 'Phone Square', 'lambry-shorts' ),
            'picture-o' => __( 'Picture O', 'lambry-shorts' ),
            'pie-chart' => __( 'Pie Chart', 'lambry-shorts' ),
            'pied-piper' => __( 'Pied Piper', 'lambry-shorts' ),
            'pied-piper-alt' => __( 'Pied Piper Alt', 'lambry-shorts' ),
            'pinterest' => __( 'Pinterest', 'lambry-shorts' ),
            'pinterest-p' => __( 'Pinterest P', 'lambry-shorts' ),
            'pinterest-square' => __( 'Pinterest Square', 'lambry-shorts' ),
            'plane' => __( 'Plane', 'lambry-shorts' ),
            'play' => __( 'Play', 'lambry-shorts' ),
            'play-circle' => __( 'Play Circle', 'lambry-shorts' ),
            'play-circle-o' => __( 'Play Circle O', 'lambry-shorts' ),
            'plug' => __( 'Plug', 'lambry-shorts' ),
            'plus' => __( 'Plus', 'lambry-shorts' ),
            'plus-circle' => __( 'Plus Circle', 'lambry-shorts' ),
            'plus-square' => __( 'Plus Square', 'lambry-shorts' ),
            'plus-square-o' => __( 'Plus Square O', 'lambry-shorts' ),
            'power-off' => __( 'Power Off', 'lambry-shorts' ),
            'print' => __( 'Print', 'lambry-shorts' ),
            'puzzle-piece' => __( 'Puzzle Piece', 'lambry-shorts' ),
            'qq' => __( 'Qq', 'lambry-shorts' ),
            'qrcode' => __( 'Qrcode', 'lambry-shorts' ),
            'question' => __( 'Question', 'lambry-shorts' ),
            'question-circle' => __( 'Question Circle', 'lambry-shorts' ),
            'quote-left' => __( 'Quote Left', 'lambry-shorts' ),
            'quote-right' => __( 'Quote Right', 'lambry-shorts' ),
            'random' => __( 'Random', 'lambry-shorts' ),
            'rebel' => __( 'Rebel', 'lambry-shorts' ),
            'recycle' => __( 'Recycle', 'lambry-shorts' ),
            'reddit' => __( 'Reddit', 'lambry-shorts' ),
            'reddit-square' => __( 'Reddit Square', 'lambry-shorts' ),
            'refresh' => __( 'Refresh', 'lambry-shorts' ),
            'registered' => __( 'Registered', 'lambry-shorts' ),
            'renren' => __( 'Renren', 'lambry-shorts' ),
            'repeat' => __( 'Repeat', 'lambry-shorts' ),
            'reply' => __( 'Reply', 'lambry-shorts' ),
            'reply-all' => __( 'Reply All', 'lambry-shorts' ),
            'retweet' => __( 'Retweet', 'lambry-shorts' ),
            'road' => __( 'Road', 'lambry-shorts' ),
            'rocket' => __( 'Rocket', 'lambry-shorts' ),
            'rss' => __( 'Rss', 'lambry-shorts' ),
            'rss-square' => __( 'Rss Square', 'lambry-shorts' ),
            'rub' => __( 'Rub', 'lambry-shorts' ),
            'safari' => __( 'Safari', 'lambry-shorts' ),
            'scissors' => __( 'Scissors', 'lambry-shorts' ),
            'search' => __( 'Search', 'lambry-shorts' ),
            'search-minus' => __( 'Search Minus', 'lambry-shorts' ),
            'search-plus' => __( 'Search Plus', 'lambry-shorts' ),
            'sellsy' => __( 'Sellsy', 'lambry-shorts' ),
            'server' => __( 'Server', 'lambry-shorts' ),
            'share' => __( 'Share', 'lambry-shorts' ),
            'share-alt' => __( 'Share Alt', 'lambry-shorts' ),
            'share-alt-square' => __( 'Share Alt Square', 'lambry-shorts' ),
            'share-square' => __( 'Share Square', 'lambry-shorts' ),
            'share-square-o' => __( 'Share Square O', 'lambry-shorts' ),
            'shield' => __( 'Shield', 'lambry-shorts' ),
            'ship' => __( 'Ship', 'lambry-shorts' ),
            'shirtsinbulk' => __( 'Shirtsinbulk', 'lambry-shorts' ),
            'shopping-cart' => __( 'Shopping Cart', 'lambry-shorts' ),
            'sign-in' => __( 'Sign In', 'lambry-shorts' ),
            'sign-out' => __( 'Sign Out', 'lambry-shorts' ),
            'signal' => __( 'Signal', 'lambry-shorts' ),
            'simplybuilt' => __( 'Simplybuilt', 'lambry-shorts' ),
            'sitemap' => __( 'Sitemap', 'lambry-shorts' ),
            'skyatlas' => __( 'Skyatlas', 'lambry-shorts' ),
            'skype' => __( 'Skype', 'lambry-shorts' ),
            'slack' => __( 'Slack', 'lambry-shorts' ),
            'sliders' => __( 'Sliders', 'lambry-shorts' ),
            'slideshare' => __( 'Slideshare', 'lambry-shorts' ),
            'smile-o' => __( 'Smile O', 'lambry-shorts' ),
            'sort' => __( 'Sort', 'lambry-shorts' ),
            'sort-alpha-asc' => __( 'Sort Alpha Asc', 'lambry-shorts' ),
            'sort-alpha-desc' => __( 'Sort Alpha Desc', 'lambry-shorts' ),
            'sort-amount-asc' => __( 'Sort Amount Asc', 'lambry-shorts' ),
            'sort-amount-desc' => __( 'Sort Amount Desc', 'lambry-shorts' ),
            'sort-asc' => __( 'Sort Asc', 'lambry-shorts' ),
            'sort-desc' => __( 'Sort Desc', 'lambry-shorts' ),
            'sort-numeric-asc' => __( 'Sort Numeric Asc', 'lambry-shorts' ),
            'sort-numeric-desc' => __( 'Sort Numeric Desc', 'lambry-shorts' ),
            'soundcloud' => __( 'Soundcloud', 'lambry-shorts' ),
            'space-shuttle' => __( 'Space Shuttle', 'lambry-shorts' ),
            'spinner' => __( 'Spinner', 'lambry-shorts' ),
            'spoon' => __( 'Spoon', 'lambry-shorts' ),
            'spotify' => __( 'Spotify', 'lambry-shorts' ),
            'square' => __( 'Square', 'lambry-shorts' ),
            'square-o' => __( 'Square O', 'lambry-shorts' ),
            'stack-exchange' => __( 'Stack Exchange', 'lambry-shorts' ),
            'stack-overflow' => __( 'Stack Overflow', 'lambry-shorts' ),
            'star' => __( 'Star', 'lambry-shorts' ),
            'star-half' => __( 'Star Half', 'lambry-shorts' ),
            'star-half-o' => __( 'Star Half O', 'lambry-shorts' ),
            'star-o' => __( 'Star O', 'lambry-shorts' ),
            'steam' => __( 'Steam', 'lambry-shorts' ),
            'steam-square' => __( 'Steam Square', 'lambry-shorts' ),
            'step-backward' => __( 'Step Backward', 'lambry-shorts' ),
            'step-forward' => __( 'Step Forward', 'lambry-shorts' ),
            'stethoscope' => __( 'Stethoscope', 'lambry-shorts' ),
            'sticky-note' => __( 'Sticky Note', 'lambry-shorts' ),
            'sticky-note-o' => __( 'Sticky Note O', 'lambry-shorts' ),
            'stop' => __( 'Stop', 'lambry-shorts' ),
            'street-view' => __( 'Street View', 'lambry-shorts' ),
            'strikethrough' => __( 'Strikethrough', 'lambry-shorts' ),
            'stumbleupon' => __( 'Stumbleupon', 'lambry-shorts' ),
            'stumbleupon-circle' => __( 'Stumbleupon Circle', 'lambry-shorts' ),
            'subscript' => __( 'Subscript', 'lambry-shorts' ),
            'subway' => __( 'Subway', 'lambry-shorts' ),
            'suitcase' => __( 'Suitcase', 'lambry-shorts' ),
            'sun-o' => __( 'Sun O', 'lambry-shorts' ),
            'superscript' => __( 'Superscript', 'lambry-shorts' ),
            'table' => __( 'Table', 'lambry-shorts' ),
            'tablet' => __( 'Tablet', 'lambry-shorts' ),
            'tachometer' => __( 'Tachometer', 'lambry-shorts' ),
            'tag' => __( 'Tag', 'lambry-shorts' ),
            'tags' => __( 'Tags', 'lambry-shorts' ),
            'tasks' => __( 'Tasks', 'lambry-shorts' ),
            'taxi' => __( 'Taxi', 'lambry-shorts' ),
            'television' => __( 'Television', 'lambry-shorts' ),
            'tencent-weibo' => __( 'Tencent Weibo', 'lambry-shorts' ),
            'terminal' => __( 'Terminal', 'lambry-shorts' ),
            'text-height' => __( 'Text Height', 'lambry-shorts' ),
            'text-width' => __( 'Text Width', 'lambry-shorts' ),
            'th' => __( 'Th', 'lambry-shorts' ),
            'th-large' => __( 'Th Large', 'lambry-shorts' ),
            'th-list' => __( 'Th List', 'lambry-shorts' ),
            'thumb-tack' => __( 'Thumb Tack', 'lambry-shorts' ),
            'thumbs-down' => __( 'Thumbs Down', 'lambry-shorts' ),
            'thumbs-o-down' => __( 'Thumbs O Down', 'lambry-shorts' ),
            'thumbs-o-up' => __( 'Thumbs O Up', 'lambry-shorts' ),
            'thumbs-up' => __( 'Thumbs Up', 'lambry-shorts' ),
            'ticket' => __( 'Ticket', 'lambry-shorts' ),
            'times' => __( 'Times', 'lambry-shorts' ),
            'times-circle' => __( 'Times Circle', 'lambry-shorts' ),
            'times-circle-o' => __( 'Times Circle O', 'lambry-shorts' ),
            'tint' => __( 'Tint', 'lambry-shorts' ),
            'toggle-off' => __( 'Toggle Off', 'lambry-shorts' ),
            'toggle-on' => __( 'Toggle On', 'lambry-shorts' ),
            'trademark' => __( 'Trademark', 'lambry-shorts' ),
            'train' => __( 'Train', 'lambry-shorts' ),
            'transgender' => __( 'Transgender', 'lambry-shorts' ),
            'transgender-alt' => __( 'Transgender Alt', 'lambry-shorts' ),
            'trash' => __( 'Trash', 'lambry-shorts' ),
            'trash-o' => __( 'Trash O', 'lambry-shorts' ),
            'tree' => __( 'Tree', 'lambry-shorts' ),
            'trello' => __( 'Trello', 'lambry-shorts' ),
            'tripadvisor' => __( 'Tripadvisor', 'lambry-shorts' ),
            'trophy' => __( 'Trophy', 'lambry-shorts' ),
            'truck' => __( 'Truck', 'lambry-shorts' ),
            'try' => __( 'Try', 'lambry-shorts' ),
            'tty' => __( 'Tty', 'lambry-shorts' ),
            'tumblr' => __( 'Tumblr', 'lambry-shorts' ),
            'tumblr-square' => __( 'Tumblr Square', 'lambry-shorts' ),
            'twitch' => __( 'Twitch', 'lambry-shorts' ),
            'twitter' => __( 'Twitter', 'lambry-shorts' ),
            'twitter-square' => __( 'Twitter Square', 'lambry-shorts' ),
            'umbrella' => __( 'Umbrella', 'lambry-shorts' ),
            'underline' => __( 'Underline', 'lambry-shorts' ),
            'undo' => __( 'Undo', 'lambry-shorts' ),
            'university' => __( 'University', 'lambry-shorts' ),
            'unlock' => __( 'Unlock', 'lambry-shorts' ),
            'unlock-alt' => __( 'Unlock Alt', 'lambry-shorts' ),
            'upload' => __( 'Upload', 'lambry-shorts' ),
            'usd' => __( 'Usd', 'lambry-shorts' ),
            'user' => __( 'User', 'lambry-shorts' ),
            'user-md' => __( 'User Md', 'lambry-shorts' ),
            'user-plus' => __( 'User Plus', 'lambry-shorts' ),
            'user-secret' => __( 'User Secret', 'lambry-shorts' ),
            'user-times' => __( 'User Times', 'lambry-shorts' ),
            'users' => __( 'Users', 'lambry-shorts' ),
            'venus' => __( 'Venus', 'lambry-shorts' ),
            'venus-double' => __( 'Venus Double', 'lambry-shorts' ),
            'venus-mars' => __( 'Venus Mars', 'lambry-shorts' ),
            'viacoin' => __( 'Viacoin', 'lambry-shorts' ),
            'video-camera' => __( 'Video Camera', 'lambry-shorts' ),
            'vimeo' => __( 'Vimeo', 'lambry-shorts' ),
            'vimeo-square' => __( 'Vimeo Square', 'lambry-shorts' ),
            'vine' => __( 'Vine', 'lambry-shorts' ),
            'vk' => __( 'Vk', 'lambry-shorts' ),
            'volume-down' => __( 'Volume Down', 'lambry-shorts' ),
            'volume-off' => __( 'Volume Off', 'lambry-shorts' ),
            'volume-up' => __( 'Volume Up', 'lambry-shorts' ),
            'weibo' => __( 'Weibo', 'lambry-shorts' ),
            'weixin' => __( 'Weixin', 'lambry-shorts' ),
            'whatsapp' => __( 'Whatsapp', 'lambry-shorts' ),
            'wheelchair' => __( 'Wheelchair', 'lambry-shorts' ),
            'wifi' => __( 'Wifi', 'lambry-shorts' ),
            'wikipedia-w' => __( 'Wikipedia W', 'lambry-shorts' ),
            'windows' => __( 'Windows', 'lambry-shorts' ),
            'wordpress' => __( 'Wordpress', 'lambry-shorts' ),
            'wrench' => __( 'Wrench', 'lambry-shorts' ),
            'xing' => __( 'Xing', 'lambry-shorts' ),
            'xing-square' => __( 'Xing Square', 'lambry-shorts' ),
            'y-combinator' => __( 'Y Combinator', 'lambry-shorts' ),
            'yahoo' => __( 'Yahoo', 'lambry-shorts' ),
            'yelp' => __( 'Yelp', 'lambry-shorts' ),
            'youtube' => __( 'Youtube', 'lambry-shorts' ),
            'youtube-play' => __( 'Youtube Play', 'lambry-shorts' ),
            'youtube-square' => __( 'Youtube Square', 'lambry-shorts' )
        ];

        return apply_filters( 'lambry_shorts_icons', $icons );

	}

}
